version: '3'

services: 
  oracle:
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - 1521:1521
      - 5500:5500

  php:
    build: dockerfiles/php
    ports:
      - 80:80
    volumes:
      - ./app/:/var/www/html
    expose:
      - "80"
